apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  labels:
    cluster: ocp-a
    zone: zone-1
  name: ocp-a-zone-1
  namespace: clusters
spec:
  clusterName: ocp-a
  management:
    autoRepair: false
    upgradeType: Replace
  platform:
    agent:
      agentLabelSelector:
        matchLabels:
          zone: zone-1
    type: Agent
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.13-x86_64
  replicas: 5
